/*APP ACTIONS HERE*/
/*APP ACTIONS HERE*/
/*APP ACTIONS HERE*/

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CONDITIONS = 'GET_CONDITIONS';
export const GET_ITEMS = 'GET_ITEMS';
export const GET_STATUSES = 'GET_STATUSES';
export const GET_USERS = 'GET_USERS';